name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        run: |
          ./docker.sh BUILD

      - name: Checkout Buildroot
        run: |
          git clone git://git.buildroot.net/buildroot

      - name: Build Buildroot
        run: |
          ./docker.sh ./build.sh
