name: Docker

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Container
        run: |
          ./docker.sh BUILD

      - name: Run a multi-line script
        run: |
          ./docker.sh ./build.sh
